//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDR.Resources.PDR.Domain.Services.PDF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PDFRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PDFRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDR.Resources.PDR.Domain.Services.PDF.PDFRes", typeof(PDFRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer signature authorizes the repairs to be completed by {0}..
        /// </summary>
        public static string EstimateSignatureMessage {
            get {
                return ResourceManager.GetString("EstimateSignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTIMATE GOOD FOR 90 DAYS..
        /// </summary>
        public static string EstimateTextInTheBox {
            get {
                return ResourceManager.GetString("EstimateTextInTheBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hereby acknowledge the satisfactory completion of the described work..
        /// </summary>
        public static string RepairOrderSignatureMessage {
            get {
                return ResourceManager.GetString("RepairOrderSignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} agrees to repair the hail damage as described to the satisfaction of the owner upon completion. {0} Guarantees not to alter the vehicle color and that vehicle&apos;s paint will not fade or peel as a result of the repairs. {0} further guarantees that the dents repaired will not return for as long as you own your vehicle..
        /// </summary>
        public static string RepairOrderTextInTheBoxGuarantee {
            get {
                return ResourceManager.GetString("RepairOrderTextInTheBoxGuarantee", resourceCulture);
            }
        }
    }
}
