//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDR.Resources.PDR.Domain.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CarInspectionsInfoRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CarInspectionsInfoRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDR.Resources.PDR.Domain.Model.CarInspectionsInfoRes", typeof(CarInspectionsInfoRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminium.
        /// </summary>
        public static string Aluminium {
            get {
                return ResourceManager.GetString("Aluminium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrosion protection.
        /// </summary>
        public static string CorrosionProtection {
            get {
                return ResourceManager.GetString("CorrosionProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom lines:.
        /// </summary>
        public static string CustomLines {
            get {
                return ResourceManager.GetString("CustomLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dents amount:.
        /// </summary>
        public static string DentsAmount {
            get {
                return ResourceManager.GetString("DentsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dents size:.
        /// </summary>
        public static string DentsSize {
            get {
                return ResourceManager.GetString("DentsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double metal.
        /// </summary>
        public static string DoubleMetal {
            get {
                return ResourceManager.GetString("DoubleMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversized dents:.
        /// </summary>
        public static string OversizedDents {
            get {
                return ResourceManager.GetString("OversizedDents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prior damages:.
        /// </summary>
        public static string PriorDamages {
            get {
                return ResourceManager.GetString("PriorDamages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total effort:.
        /// </summary>
        public static string TotalEffort {
            get {
                return ResourceManager.GetString("TotalEffort", resourceCulture);
            }
        }
    }
}
