//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDR.Resources.Web.Area.Estimator.Validators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RetailCustomerModelValidatorRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RetailCustomerModelValidatorRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDR.Resources.Web.Area.Estimator.Validators.RetailCustomerModelValidatorRes", typeof(RetailCustomerModelValidatorRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only letters.
        /// </summary>
        public static string FirstNameInvalidSymbolsPresented {
            get {
                return ResourceManager.GetString("FirstNameInvalidSymbolsPresented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter up to 25 letters.
        /// </summary>
        public static string FirstNameMaxLengthWasReached {
            get {
                return ResourceManager.GetString("FirstNameMaxLengthWasReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a first name.
        /// </summary>
        public static string FirstNameMustBeNotEmpty {
            get {
                return ResourceManager.GetString("FirstNameMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only letters.
        /// </summary>
        public static string LastNameInvalidSymbolsPresented {
            get {
                return ResourceManager.GetString("LastNameInvalidSymbolsPresented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter up to 35 letters.
        /// </summary>
        public static string LastNameMaxLengthWasReached {
            get {
                return ResourceManager.GetString("LastNameMaxLengthWasReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a last name.
        /// </summary>
        public static string LastNameMustBeNotEmpty {
            get {
                return ResourceManager.GetString("LastNameMustBeNotEmpty", resourceCulture);
            }
        }
    }
}
